"""empty message

Revision ID: c669e2b87523
Revises: de989770696f
Create Date: 2019-03-18 02:56:22.402390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c669e2b87523'
down_revision = 'de989770696f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('biography', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('date', sa.String(length=12), nullable=True))
    op.add_column('user_profiles', sa.Column('location', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('photo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'photo')
    op.drop_column('user_profiles', 'location')
    op.drop_column('user_profiles', 'date')
    op.drop_column('user_profiles', 'biography')
    # ### end Alembic commands ###
